package Vista;

import Controlador.Controlador_Productos;
import Modelo.Producto_model;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author jhony
 */
public class BuscarProductoStock extends javax.swing.JInternalFrame {

    Controlador_Productos ProductoController = new Controlador_Productos();
    Producto_model ProductoModel = new Producto_model();
    String path = "";
    
    public BuscarProductoStock() {
        initComponents();
        ProductoController.buscarRegistroProducto(TbBuscar); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txt_Contenido_neto = new javax.swing.JTextField();
        txt_Descripcion = new javax.swing.JTextField();
        txt_Precio = new javax.swing.JTextField();
        txt_Stock = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Foto = new javax.swing.JLabel();
        lblNombreImagen = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        COMBOOPCION = new javax.swing.JComboBox<>();
        txtBuscarN = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbBuscar = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setForeground(new java.awt.Color(0, 51, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar Productos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(251, 248, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 30, 160, -1));

        txtMarca.setEditable(false);
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 93, 167, -1));

        txt_Contenido_neto.setEditable(false);
        jPanel3.add(txt_Contenido_neto, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 124, 167, -1));

        txt_Descripcion.setEditable(false);
        jPanel3.add(txt_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 155, 167, -1));

        txt_Precio.setEditable(false);
        jPanel3.add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 220, 167, -1));

        txt_Stock.setEditable(false);
        jPanel3.add(txt_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 189, 167, -1));

        jLabel1.setText("ID_Producto:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 36, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 68, -1, -1));

        jLabel4.setText("Marca:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 96, -1, -1));

        jLabel5.setText("Stock:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 192, -1, -1));

        jLabel6.setText("Descripcion:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 158, -1, -1));

        jLabel7.setText("Contenido_Neto:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 127, -1, -1));

        jLabel10.setText("Precio:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 223, -1, -1));

        jLabel_Foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FotoMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 270, 160));
        jPanel3.add(lblNombreImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        txtNombre.setEditable(false);
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 62, 167, -1));

        COMBOOPCION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "ID", "Marca", "Producto eliminado" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/buscar.png"))); // NOI18N
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        TbBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(COMBOOPCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtBuscarN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(COMBOOPCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FotoMouseClicked

    }//GEN-LAST:event_jLabel_FotoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(COMBOOPCION.getSelectedItem()=="Nombre"){
            ProductoController.buscarRegistroNombreProducto(txtBuscarN.getText(), TbBuscar);
        }else if(COMBOOPCION.getSelectedItem()=="ID"){
            ProductoController.buscarRegistroIDProducto(txtBuscarN.getText(), TbBuscar);
        }else if(COMBOOPCION.getSelectedItem()=="Marca"){
            ProductoController.buscarRegistroMarcaProducto(txtBuscarN.getText(), TbBuscar);
        }else{
            ProductoController.buscarRegistroProductoEliminado(txtBuscarN.getText(), TbBuscar);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbBuscarMouseClicked
        txtId.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),0).toString());
        txtNombre.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),1).toString());
        txtMarca.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),2).toString());
        txt_Contenido_neto.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),3).toString());
        txt_Descripcion.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),4).toString());
        txt_Stock.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),5).toString());
        txt_Precio.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),6).toString());
        //buscar la imagen del producto seleccionado
        int id = Integer.parseInt(txtId.getText());
        ProductoModel.setID_Productos(id);
        ProductoController.BuscarImageProd(ProductoModel);
        //Convertir una cadena de Bytes a una imagen
        byte[] ImagenMod = ProductoModel.getImagen();
        BufferedImage img1 = null;
        try{
            img1 = ImageIO.read(new ByteArrayInputStream(ImagenMod));
            //Mostrar la imagen traida de la base de datos a un label
            jLabel_Foto.setIcon(new ImageIcon(img1));
            ImageIcon icon = new ImageIcon(img1);
            Image img = icon.getImage();
            Image newimg = img.getScaledInstance(jLabel_Foto.getWidth(), jLabel_Foto.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newimg);
            jLabel_Foto.setIcon(newIcon);
            jLabel_Foto.setSize(jLabel_Foto.getWidth(), jLabel_Foto.getHeight());
        } catch (IOException ex) {
            Logger.getLogger(ProductoRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        String NombrePro = TbBuscar.getValueAt(TbBuscar.getSelectedRow(),1).toString();
        String MarcaPro = TbBuscar.getValueAt(TbBuscar.getSelectedRow(),2).toString();
        //enviar datos a actualizar stock
        AgregarStock.txtIdPro.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),0).toString());
        AgregarStock.txtNombrePro.setText(NombrePro + " || " + MarcaPro);
        AgregarStock.txt_StockActual.setText(TbBuscar.getValueAt(TbBuscar.getSelectedRow(),5).toString());       
    }//GEN-LAST:event_TbBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMBOOPCION;
    public static javax.swing.JTable TbBuscar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Foto;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreImagen;
    private javax.swing.JTextField txtBuscarN;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txt_Contenido_neto;
    private javax.swing.JTextField txt_Descripcion;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_Stock;
    // End of variables declaration//GEN-END:variables
}
