package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jdk.nashorn.internal.codegen.CompilerConstants;

/**
 *
 * @author jhony
 */
public class MenuVendedores extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menuV;
    /**
     * Creates new form Menu1
     */
    public MenuVendedores() {
        initComponents();
       //Codigo para ajustar el menu con la resolucion de pantalla
       this.setSize(new Dimension(1200, 700));
       this.setExtendedState(this.MAXIMIZED_BOTH);
       this.setLocationRelativeTo(null);
       this.setTitle("Sistema de Ventas");
       
       //codigo para que el jInternal se muestre en el menu con las dimenciones de la resolucion de la pantalla
        this.setLayout(null);
        jDesktopPane_menuV = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menuV.setBounds(0, 0, ancho, (alto - 90));
        this.jDesktopPane_menuV.setBackground(Color.darkGray);
        
        this.add(jDesktopPane_menuV);
    }
    
    @Override
    public Image getIconImage (){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("AImagenes/IconoLogoGeneral.png"));
    return retValue;
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuConsultarCliente = new javax.swing.JMenuItem();
        MenuConsultaProducto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        VentasMenu = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        MnuAdministrador = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuPerfil = new javax.swing.JMenu();
        mnuAdminPerfil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentX(4.0F);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(220, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(212, 35));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/MenuArchivo.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/sa1.png"))); // NOI18N
        jMenuItem8.setText("Cerrar Sesión");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/ce2.png"))); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/MenuConsultas.png"))); // NOI18N
        jMenu5.setText("Consultas");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        MenuConsultarCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MenuConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/cons2.png"))); // NOI18N
        MenuConsultarCliente.setText("Clientes");
        MenuConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(MenuConsultarCliente);

        MenuConsultaProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MenuConsultaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/cons5.png"))); // NOI18N
        MenuConsultaProducto.setText("Productos");
        MenuConsultaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuConsultaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaProductoActionPerformed(evt);
            }
        });
        jMenu5.add(MenuConsultaProducto);

        jMenuBar1.add(jMenu5);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/mov.png"))); // NOI18N
        jMenu3.setText("Movimiento");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        VentasMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        VentasMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        VentasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/vent1.png"))); // NOI18N
        VentasMenu.setText("Ventas");
        VentasMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VentasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasMenuActionPerformed(evt);
            }
        });
        jMenu3.add(VentasMenu);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/caja1.png"))); // NOI18N
        jMenuItem24.setText("Caja");
        jMenuItem24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuBar1.add(jMenu3);

        MnuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/adm.png"))); // NOI18N
        MnuAdministrador.setText("Administrador");
        MnuAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MnuAdministrador.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/us1.png"))); // NOI18N
        jMenuItem10.setText("Nuevo Cliente");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MnuAdministrador.add(jMenuItem10);

        jMenuBar1.add(MnuAdministrador);

        mnuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/per.png"))); // NOI18N
        mnuPerfil.setText("Perfil");
        mnuPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuPerfil.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        mnuAdminPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnuAdminPerfil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuAdminPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AImagenes/con1.png"))); // NOI18N
        mnuAdminPerfil.setText("Administrar Perfil");
        mnuAdminPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuAdminPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAdminPerfilMouseClicked(evt);
            }
        });
        mnuAdminPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminPerfilActionPerformed(evt);
            }
        });
        mnuPerfil.add(mnuAdminPerfil);

        jMenuBar1.add(mnuPerfil);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Login regresar = new Login();
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void VentasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasMenuActionPerformed
       Ventas NuevaVent = new Ventas();
       agregarFrameCentrado(NuevaVent, jDesktopPane_menuV);
    }//GEN-LAST:event_VentasMenuActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
       Caja AbrirCaj = new Caja();
       agregarFrameCentrado(AbrirCaj, jDesktopPane_menuV);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void mnuAdminPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAdminPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAdminPerfilMouseClicked

    private void mnuAdminPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminPerfilActionPerformed
        AdministrarPerfil adminPerfil = new AdministrarPerfil();
        agregarFrameCentrado(adminPerfil, jDesktopPane_menuV);
    }//GEN-LAST:event_mnuAdminPerfilActionPerformed

    private void MenuConsultaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaProductoActionPerformed
        BuscarProducto ConsulPro = new BuscarProducto();
        agregarFrameCentrado(ConsulPro, jDesktopPane_menuV);
    }//GEN-LAST:event_MenuConsultaProductoActionPerformed

    private void MenuConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarClienteActionPerformed
        BuscarCliente ConsulClie = new BuscarCliente();
        agregarFrameCentrado(ConsulClie, jDesktopPane_menuV);
    }//GEN-LAST:event_MenuConsultarClienteActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        NuevoCliente nuevousu = new NuevoCliente();
        agregarFrameCentrado(nuevousu, jDesktopPane_menuV);
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    
    public void agregarFrameCentrado(JInternalFrame frame, JDesktopPane desktopPane) {
        desktopPane.add(frame);           
        Dimension desktopSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();
        frame.setLocation((desktopSize.width - frameSize.width)/2, (desktopSize.height- frameSize.height)/2);
        frame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVendedores().setVisible(true);
            }           
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuConsultaProducto;
    private javax.swing.JMenuItem MenuConsultarCliente;
    public static javax.swing.JMenu MnuAdministrador;
    private javax.swing.JMenuItem VentasMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JMenuItem mnuAdminPerfil;
    public static javax.swing.JMenu mnuPerfil;
    // End of variables declaration//GEN-END:variables
}
